### ISSUE TITLE
Topic names different for gazebo and real robot

### ISSUE THREAD

**Issue by maxspahn** [INTERACT-tud-amr/dinova#1]
Some of the topic names are different for the gazebo simulation and for the real robot.
For example: `/dinova/command` in the real world vs `/joints_position_controller/command` in the simulator. As the latter cannot be changed easily, see https://github.com/ros-controls/ros_controllers/issues/126, we should consider changing the topic names for the real robot.

Having the same topic eases the transfer of algorithms between both systems.

**Comment by TomasMerva** [comment]
Commit 930a34a0e2fbea1f23b552ed587599a8a702e8a1
Since I cannot have the same topic name for position and velocity controllers, the topic for the velocity controller for kinova/dinova is called: `/kinova/command`. It expects the same message type as the real robot. 

The topic for controlling dingo in Gazebo is called `/omnidrive_velocity_controller/command` but the real robot has the topic called `/cmd_vel`. The best I can do is change the Gazebo topic into `/cmd_vel/command` but I don't know if it is beneficial.
